language: android
jdk: oraclejdk8
before_cache:
  - 'rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock'
  - 'rm -fr $HOME/.gradle/caches/*/plugin-resolution/'
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
before_install:
  - 'echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json'
  - 'chmod +x gradlew'
script:
  - './gradlew clean check --stacktrace'
